In [ ]:
# 第四章 NumPy 基础：数组和矢量计算
import numpy as np


# # 对比速度
# my_arr = np.arange(100000)
# my_list = list(my_arr)

# %time for _ in range(100): my_arr2 = my_arr * 2
# %time for _ in range(100): my_list2 = [x * 2 for x in my_list]

# # np.random随机模块 .randn标准正态分布随机数
# data = np.random.randn(2,3) 
# print(data)
# print(data * 10)
# data + data

# data.shape # 查看维度大小 (2, 3)
# data.dtype # 查看数据类型 ('float64')

# # 创建数组
# data1 = [6, 7, 8, 9, 10.1]
# arr1 = np.array(data1)
# arr1
# arr1.dtype # float64, because have 10.1

# data2 = [[1,3,5,7,9], [2,4,6,8,10]]
# arr2 = np.array(data2)
# arr2
# arr2.ndim # 维度 2
# arr2.shape
# arr2.dtype # int64

# np.zeros(10)
# np.zeros((2,3))
# np.empty((3,3)) # 分配内存空间但不填充任何值 初始值为内部残留值
# np.arange(10)   # range的数组版
# np.ones(10)     # 

# # dtype=np.~ 改变数据类型
# arr3 = np.array([1, 2, 3, 4], dtype=np.float64) # change the 数据类型
# arr3.dtype

# arr4 = np.array([3.7, -2.1, 9.0, 0.5, 10.1]) # 浮点数变整数会截取小数部分
# arr4 = arr4.astype(np.int64)                 # astype 改变数据类型
# arr4.dtype
# arr4

In [ ]:
# 数组的运算
data5 = ([1,2,3], [4,5,6])
arr5 = np.array(data5)
print(arr5)
arr5 * arr5
arr5 / arr5
arr5 - arr5
arr5 + arr5
1 / arr5
arr5 ** 0.5
data6 = ([3,2,1], [6,5,2])
arr6 = np.array(data6)
print(arr6)
arr6 == arr5
arr6 > arr5

In [83]:
# 基本的索引和切片
arr7 = np.arange(10)
print(arr7)
arr7[5]  # 5
arr7[5:8]
arr7[5:8] = 1
arr7_slice = arr7[5:8]
arr7_slice[1] = 10101
arr7_slice
arr7

# 高维
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)
arr2d[1] # 索引列表 
arr2d
arr2d[1,1] # 索引列表中的标量 

arr3d = np.array([[[1,2,3,], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr3d)
arr3d[0]

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[1, 2, 3],
       [4, 5, 6]])